sudo: required

branches:
  only:
    - master

language: c++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - clang
    - gcc
  script:
    - ./scripts/run_tests.sh $CC $CXX

script:
  - bash ./scripts/travis.sh